# Generated by Django 3.1.1 on 2020-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='requesttrade',
            name='item_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesttrade',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Closed'), ('2', 'Declined'), ('3', 'Accepted')], default=0, max_length=1),
        ),
    ]
